---
- name: get OS from get_facts
  hosts: all
  become: true
  become_user: root
  gather_facts: yes
  tasks:
    - name: check os distribution
      debug:
        msg: OS Version = {{ ansible_distribution  }} {{ ansible_distribution_version }} {{ ansible_distribution_release}}
